### ISSUE TITLE
Website scaling

### ISSUE THREAD

**Issue by superfirepig** [ShifuYee/Bowie-Internal-Medicine-Website#15]
Run the site under google developer tools and activate simulate mobile environment. Most android phone these days are 1440p. I am seeing some mobile responsiveness issue for the header and body. I have not looked at the css in its entirety but I would suggest to use % ratio for div length instead of using px for best compatibility. Otherwise you will need too many css lines attributed to identifying different screen size.

**Comment by superfirepig** [comment]
Your CSS for width of the body should look something like

div {
width: 50%
}

^allows the content occupy 50% of the screen always


you can then use padding or margin to define where things should be such as 

p {
margin-right: auto;
margin-left: auto;
}

that will center the content

**Comment by ShifuYee** [comment]
Pull-request #17 resolves issue #15
